site_name: Khalti Services Documentation
nav:
  - Introduction: index.md
  - Service Layer State: Servicescodes/statecode.md
  - Khalti Topup: Khaltitopup/khaltitopup.md
  - Mobile TopUp:
        - Nepal Telecom: MobileTopup/nepal_telecom.md
        - Ncell: MobileTopup/ncell.md
  - Electricity: Electricity/nea.md
  - PSTN (Landline): PSTN/landline.md
  - Khanepani: Khanepani/khanepani.md
 
  - TV :
    - SimTV: TV/simtv.md
    - Max Tv: TV/maxtv.md
    - Prabhu Tv: TV/Prabhutv.md
    - P & G Network: TV/p&g.md
    - Jagriti Cable: TV/jagrititv.md
    - Times: TV/times.md
  - Internet:
    - Worldlink: Internet/worldlink.md
    - Vianet: Internet/vianet.md
    - Adsl: Internet/adsl.md
    - Subisu: Internet/subisu.md
    - Classic Tech: Internet/classictech.md
    - Times Internet: Internet/timesinternet.md
    - Arrownet: Internet/arrownet.md
  - Insurance: 
      - Non life Insurances:
          - Arhant Non-Life Insurances: Insurance/Arhant Insurance/non_life.md 
          - Prudential Insurance: Insurance/prudential/prudential.md
          - Neco Insurance:  Insurance/neco_insurance.md
          - Sagarmatha Lumbini Insurance: Insurance/sagarmatha_insurance.md
          - Nepal Non Life Insurance: Insurance/nepal_non_life.md
  
      - Life Insurances:
        - Arhant Life Insurance : Insurance/Arhant Insurance/life.md 
        - Surya Life Insurance: Insurance/surya/Suryalife.md
        - Sanima Insurance: Insurance/Reliance Insurance/reliance_insurance.md    
        - Sun Life Insurance: Insurance/Sunlife/sunlife.md
        - Rastriya Beema Sansthan: Insurance/rastriyabeema.md
        - Surya Jyoti Loan Repayment: Insurance/suryajoytiloan.md
        - Reliable Insurance: Insurance/Reliable_life.md
        - Citizen Life Insurance: Insurance/Citizen/citizen.md
        - Surya Life Insurance First Payment:  Insurance/surya/surya_life_insurance.md
        - IME General Insurance: Insurance/ime/ime_general.md
        - Prabhu Life: Insurance/prabhu_life.md
        - Nepal Life Insurance: Insurance/Nepal/nepal_Life_Insurace.md
        
  - Rc Card: Rc card/rccard.md
  - Data Packs:
      - Ncell DataPacks: datapacks/NcellProduct.md
      - NTC DataPacks: datapacks/ntcProduct.md
  - Community Electricity:
    - Himchuli Electricity: Electricity/Himchuli.md
    - Watermark Electricity: Electricity/watermark.md
    - Dreamer Electricity: Electricity/dreamer.md
    - Softlab Electricity: Electricity/softlab.md
  - Cable Car: Cable Car/cablecar.md
  - Ride:
      - CABTM: Ride/cabtm.md
      - Tottle: Ride/tootle.md
  - Bluebook: bluebook/bluebook.md
  - Service LookUp API: Servicescodes/lookup.md
  - Bulk Service Lookup: Servicescodes/bulkservice.md
  - Changelog: Servicescodes/changelog.md
  - FAQ's: Servicescodes/faq.md


theme:
  name: material
  custom_dir: overrides
  favicon: "https://d7vw40z4bofef.cloudfront.net/static/2.59.12-web19/images/favicon.png"
  icon:
    logo: "img/khalti_logo"
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
  - style/custom.css
  - style/extra.css
docs_dir: content 
site_dir: docs
repo_name: "khalti/serviceapi.docs.khalti.com"
repo_url: "https://github.com/khalti/serviceapi.docs.khalti.com/"
edit_uri: "edit/main/content/"
copyright: "Copyright &copy; 2024 Khalti Private Limited"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/khalti"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/KhaltiOfficial"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/khalti-digital-wallet"
    - icon: "fontawesome/brands/facebook"
      link: "https://facebook.com/khaltiofficial"
    - icon: "fontawesome/brands/instagram"
      link: "https://www.instagram.com/khaltiofficial/"

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences

# Uncomment and install any necessary plugins if needed
# plugins:
#   - search
#   - social
